# ~/profiles.toml
#
# Config for ResticProfile (https://creativeprojects.github.io/resticprofile/index.html)
#
#:schema https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json
#
version = "1"

[global]
run-before = [
  "echo  AWS_ACCESS_KEY_ID=\"$(op read 'op://personal/Restic Backup/aws_access_key_id')\" >> {{ env }}",
  "echo  AWS_SECRET_ACCESS_KEY=\"$(op read 'op://personal/Restic Backup/aws_secret_access_key')\" >> {{ env }}",
]

exclude-caches = true
initialize = true
one-file-system = true
password-command = "op read 'op://personal/Restic Backup/password'"
prevent-sleep = true
priority = "low"
source = [ "~" ]

[global.retention]
after-backup = true
keep-last = 5

[global.backup]
exclude = [
  "**/.DS_Store",
  "**/.Spotlight-V100",
  "**/.git",
  "**/.svn",
  "**/node_modules",
  "*.swp",
  "*.tmp",
  "*~",
  "~/.Trash",
  "~/.gradle",
  "~/.maven",
  "~/.npm",
  "~/.yarn",
  "~/Downloads",
  "~/Dropbox",
  "~/Google Drive",
  "~/Library/Application Support/Homebrew",
  "~/Library/Logs",
  "~/Music/iTunes",
  "~/OneDrive",
  "~/Parallels",
  "~/Pictures/Photos Library.photoslibrary",
  "~/VMware",
  "~/VirtualBox VMs",
]

[default]
inherit = "global"
lock = "/tmp/resticprofile-default.lock"
repository = "s3:s3.us-east-005.backblazeb2.com/rosstimson-backup"

[default.backup]
schedule = "weekly"
schedule-after-network-online = true
schedule-log = "~/Library/Logs/resticprofile-default-scheduled.log"
schedule-permission = "user"
