baseURL = "https://titan-c.gitlab.io/org-cv/"
languageCode = "en-us"
title = "Org CV"
theme = "project-landing-page"

[params]
    description = "Org-mode backend exporters for Curriculum Vita"
    author_url = "http://blog.oscarnajera.com"
    author = "Titan-C"
    project_url = "https://gitlab.com/Titan-C/org-cv/"
    logo = "https://upload.wikimedia.org/wikipedia/commons/a/a6/Org-mode-unicorn.svg"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"
