# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install stuff
install abcde --with-flac --with-lame --with-vorbis-tools
install bazaar
install bitlbee --with-finch --with-libotr
install brew-cask
install casperjs
install cscope
install csshx
install dos2unix
install elixir
install gh
install gist
install git
install git-flow
install go
install goaccess
install ipcalc
install irssi --with-openssl
install jq
install luajit
install luarocks
install macvim --with-cscope --with-luajit --override-system-vim
install mariadb
install mercurial
install mobile-shell
install mpd --with-flac --with-lame --with-vorbis
install mtr
install ncmpcpp --clock --visualizer
install nmap
install node
install notmuch
install opus
install par
install pass
install phantomjs
install pwgen
install remind
install rename
install s3cmd
install sipcalc
install the_silver_searcher
install tig
install tree
install wget
install xz

# Remove outdated versions from the cellar
cleanup
