confirm-before-quit = false
option-as-alt = 'left'
padding-x = 10

[adaptive-theme]
light = "dayfox"
dark  = "terafox"

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "rt"]

[editor]
program = "nvim"

[fonts]
size = 16
family = "Dank Mono"
additional-dirs = ["/Users/ross.timson/Library/Fonts"]
extras = [{ family = "Symbols Nerd Font Mono" }]

[window]
mode = "Maximized"

[bell]
audio = false
visual = false
