confirm-before-quit = false
option-as-alt = 'left'
padding-x = 10

[adaptive-theme]
light = "dayfox"
dark  = "terafox"

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "rt"]

[fonts]
size = 16
additional-dirs = ["/Users/ross.timson/Library/Fonts"]

[fonts.regular]
family = "BlexMono Nerd Font Mono"
style  = "Normal"
width  = "Normal"
weight = 400

[fonts.bold]
family = "BlexMono Nerd Font Mono"
style  = "Normal"
width  = "Normal"
weight = 700

[fonts.italic]
family = "BlexMono Nerd Font Mono"
style  = "Italic"
width  = "Normal"
weight = 400

[fonts.bold-italic]
family = "BlexMono Nerd Font Mono"
style  = "Italic"
width  = "Normal"
weight = 700

[window]
mode = "Maximized"

[bell]
audio = false
visual = false
