confirm-before-quit = false
option-as-alt = 'left'

[adaptive-theme]
light = "dayfox"
dark  = "terafox"

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "rt"]

[fonts]
size = 16
family = "IBM Plex Mono"

[window]
mode = "Maximized"
