# Don't print a new line at the start of the prompt
add_newline = false

# Set timeout to 1 second, default is 500 milliseconds which can cause issues
# with git prompt on larger repos.
command_timeout = 2000

# replace the "❯" symbol in the prompt with "$", keeping it old skool.
[character]
success_symbol = "\\$"
error_symbol = "x"

[cmd_duration]
style = "cyan"

[directory]
style = "green"


# Enable (modules that are disabled by default)
# ----------------------------------------------------------------------------

[direnv]
disabled = false

[custom.TGENVIRONMENT]
command = 'echo ${TG_CSP}\|${TG_CUSTOMER}\|${TG_ENVTYPE}\|${TG_ENV}'
when = ''' test -f $(git root)/root.hcl '''
format = '[\[🐽 $output\]](blue) '


# Disabled
# ----------------------------------------------------------------------------

[aws]
disabled = true

# Disable GCloud module as it permanently shows cruft in the prompt
[gcloud]
disabled = true
