# Don't print a new line at the start of the prompt
add_newline = false

# Set timeout to 1 second, default is 500 milliseconds which can cause issues
# with git prompt on larger repos.
command_timeout = 2000

# replace the "❯" symbol in the prompt with "$", keeping it old skool.
[character]
success_symbol = "[\\$](black)"
error_symbol = "x"

[cmd_duration]
style = "cyan"

[directory]
style = "green"


# Disabled
# ----------------------------------------------------------------------------

[aws]
disabled = true

# Disable GCloud module as it permanently shows cruft in the prompt
[gcloud]
disabled = true
