# Don't print a new line at the start of the prompt
add_newline = false

# Set timeout to 1 second, default is 500 milliseconds which can cause issues
# with git prompt on larger repos.
command_timeout = 2000

# replace the "❯" symbol in the prompt with "$", keeping it old skool.
[character]
success_symbol = "\\$"
error_symbol = "x"

[cmd_duration]
style = "cyan"

[directory]
style = "green"


# Enable (modules that are disabled by default)
# ----------------------------------------------------------------------------

[direnv]
disabled = false

[custom.kubernetes]
format = '[\[⛵ $output\]](cyan) '
command =  'kubectl config current-context'
when = ''' test -S ${HOME}/.ssh-master '''

[custom.causaly_env]
require_repo = true
when = ''' test -f $(git root)/root.hcl '''
command = '''
v1="$(git root)/config/"
v2=$(pwd)
if [[ "${v2}" == "${v1}"* ]]
then
  stub=${v2#$v1}
  IFS=/ read -r csp customer envtype env discard <<< ${stub}
  echo "[🐽 (${csp})${customer:+" "$customer}${envtype:+" "$envtype}${env:+" "$env}]"
fi
'''


# Disabled
# ----------------------------------------------------------------------------

[aws]
disabled = true

# Disable GCloud module as it permanently shows cruft in the prompt
[gcloud]
disabled = true
