# Don't print a new line at the start of the prompt
add_newline = false
#
# Replace the "❯" symbol in the prompt with "➜"
[character]
symbol = "➜"
error_symbol = "✖"
use_symbol_for_status = true
style_success = "black"

[aws]
symbol = "  "
style = "yellow"

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[cmd_duration]
style = "cyan"

[conda]
symbol = " "

[directory]
style = "green"

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
style = "blue"

[git_status]
deleted = "x"

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
style = "green"

[package]
symbol = " "
style = "yellow"

[php]
symbol = " "

[python]
symbol = " "
style = "yellow"

[ruby]
symbol = " "

[rust]
symbol = " "
style = "red"

[terraform]
style = "purple"
