# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](black)"
error_symbol = "✖"

[aws]
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[cmd_duration]
style = "cyan"

[conda]
symbol = " "

[custom.toolbox]
when = """ test -e /run/.toolboxenv """
format = "  in toolbox "
#command = "echo toolbox"
#prefix = "in "
#symbol = "  "

[directory]
style = "green"

[docker_context]
symbol = " "

# Disable GCloud module as it permanently shows cruft in the prompt
[gcloud]
disabled = true

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
style = "blue"

[git_status]
deleted = "x"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
style = "green"

[package]
symbol = " "
style = "yellow"

[php]
symbol = " "

[python]
symbol = " "
style = "yellow"

[ruby]
symbol = " "

[rust]
symbol = " "
style = "red"

[terraform]
style = "purple"
