[general]
import = [
    "~/.config/alacritty/themes/themes/rosstimson-muted.toml"
]

[window]
decorations = "none"
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[font]
size = 13.0

[font.bold]
family = "FiraMono Nerd Font"
style = "Regular"

[font.bold_italic]
family = "FiraMono Nerd Font"
style = "Italic"

[font.italic]
family = "FiraMono Nerd Font"
style = "Italic"

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[terminal]

[terminal.shell]
args = ["new-session", "-A", "-s", "rt"]
program = "/opt/homebrew/bin/tmux"

[window.padding]
x = 12
y = 2
